### ISSUE TITLE
v5.17.0 and MacOS Catalina 10.15

### ISSUE THREAD

**Issue by LStester** [transmission-remote-gui/transgui#1227] opened 2019-06-30 17:08 UTC
Hi pls add MacOS Catalina 10.15
but in catalina transgui not work (

thanks!

**Comment by PeterDaveHello** [comment] 2019-06-30 17:09
@LStester see #1150 #1224

**Comment by LStester** [comment] 2019-06-30 17:34
> @LStester see #1150 #1224
sorry i’am not programmer
could you compile and upload to dropbox or google disk pls?

**Comment by PeterDaveHello** [comment] 2019-06-30 17:35
@LStester nope, as you can see, it's not finished.

**Comment by LStester** [comment] 2019-06-30 17:36
> @LStester nope, as you can see, it's not finished.

thanks, i’am looking forward to support catalina in your program!

**Comment by PeterDaveHello** [comment] 2019-06-30 17:44
Close as duplicate of #1150

**Closed by PeterDaveHello** 2019-06-30 17:44 UTC
